spring.application.name=cursos

spring.datasource.url=jdbc:postgresql://localhost:5432/cursos_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configurations
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

reniec.base-url=https://api.decolecta.com/v1/reniec
renic.token=sk_16499.50gyI7t1R0w6vTLgn33cbbPvMMO90Ws6

server.port=8081
